### ISSUE TITLE
Better Questing OSS not accepting fluids

### ISSUE THREAD

**Issue by studkid** [rgtexa/Automaton#18]
I was trying to turn in the creative fluid tank quest but when I tried to import the fluids required in, nothing happened.  I have tried using Extra Cells export buses and Mekanism mechanical pipes so far and nothing would be imported.  I’ve also tried putting a bucket filled with gasoline manually in to the OSS and that still won’t work.  

Pack version: 1.3.1

[Here is some relevant pics](https://imgur.com/a/qQyo2cq)

**Comment by rgtexa** [comment]
I've confirmed the OSS is not functioning for items or fluids.

There is an [open issue](https://github.com/Funwayguy/BetterQuesting/issues/408) for this on the Better Questing Github, which I've added comments on with more information.

Unfortunately, this is an issue that will have to await the mod developer to fix.

**Comment by studkid** [comment]
Yeah, I actually found this out the other day and had intended on editing my post detailing it but forgot about it.  Either way, kind of unfortunate that it doesn’t work correctly.  Guess I’ll just need to manually complete it :/

Hope this is fixed by the BQ dev soon

**Comment by WarpZone32** [comment]
Still broken in 1.12.2 in 2019.

It's a shame.  I really wanted to do some automation-themed quests with this, but apparently it's just impossible.  

Does anybody know if the Forge version works?

Does anybody know how to tell which version of Forge a mod on Curse requires before you click the download button?
